### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by anuanu0-0** [subodhk01/a2oj#17]
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
![Screenshot (500)](https://user-images.githubusercontent.com/60839849/97262342-a4682c80-1846-11eb-9479-f056ff3036c9.png)

**Comment by subodhk01** [comment]
Thanks @anuanu0-0 for reporting the error, it has been fixed now 😁✌🏻
