### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by arun2145** [subodhk01/a2oj#18]
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail....!!!

please  fix this soon we love your dynamic a20j ladder...
....................................***..........................***......................................

**Comment by subodhk01** [comment]
On it 😁✌🏻

**Comment by subodhk01** [comment]
Fixed! Thanks for informing ✌🏻

**Comment by arun2145** [comment]
cool....
