### ISSUE TITLE
Dynamic A2OJ has stopped working but Codeforces API doesn't seem down

### ISSUE THREAD

**Issue by deepikabirthare** [subodhk01/a2oj#23]
I tried refreshing it and waited for almost a day but ladder is not showing up. 
Even Codeforces API is not down.

**Comment by atpug22** [comment]
@deepikabirthare is it working for you now? and if not then can you share the screenshot of the problem you are facing?

**Comment by deepikabirthare** [comment]
No it's still not working.

**Comment by deepikabirthare** [comment]
file:///C:/Users/DEEPIKA/OneDrive/Pictures/Screenshots/2021-03-27.png

**Comment by subodhk01** [comment]
@deepikabirthare The ss didn't get uploaded properly

**Comment by deepikabirthare** [comment]
![2021-03-27](https://user-images.githubusercontent.com/62948786/112709714-b297a300-8ee1-11eb-8da8-4fa016764598.png)

**Comment by deepikabirthare** [comment]
Sorry it got uploaded now.

**Comment by subodhk01** [comment]
Since there has been some addition to the application, your url should also include `rating` parameter. Try going directly to https://a2oj.herokuapp.com

**Comment by deepikabirthare** [comment]
This link is also not working.
It also has the same issue.

**Comment by deepikabirthare** [comment]
When I clicked on  https://a2oj.herokuapp.com same image opened up.

**Comment by deepikabirthare** [comment]
![2021-03-27 (1)](https://user-images.githubusercontent.com/62948786/112709839-9e07da80-8ee2-11eb-861f-920001b12f05.png)

**Comment by deepikabirthare** [comment]
Here is the ss of what happened after clicking on that link.

**Comment by subodhk01** [comment]
Yeah, so now you got to enter your handle and the desired ladder here

**Comment by deepikabirthare** [comment]
Ok it worked now .
Thanks a lot!

**Comment by deepikabirthare** [comment]
Dynamic A2Oj has again stopped working, please help.

**Comment by deepikabirthare** [comment]
When I enter my handle and ratings it shows invalid codeforces handle

**Comment by deepikabirthare** [comment]
And I checked codeforces API is not down now.
