### ISSUE TITLE
No such app exists

### ISSUE THREAD

**Issue by manu-shukla** [subodhk01/a2oj#27]
On opening the link, it says no such app exists. Is dynamic A2oJ removed??
![Screenshot 2021-04-18 002302](https://user-images.githubusercontent.com/18571875/115123804-5570a800-9fdc-11eb-9a61-9cb18266aad8.jpg)

**Comment by subodhk01** [comment]
Actually my account has been suspended for some reason, I'm currently looking into the problem. Till then you can use https://a2ojj.herokuapp.com/

**Comment by manu-shukla** [comment]
> Actually my account has been suspended for some reason, I'm currently looking into the problem. Till then you can use https://a2ojj.herokuapp.com/

Thanks a lot!
