### ISSUE TITLE
Showing invalid codeforces handle on for any handle

### ISSUE THREAD

**Issue by codepiyush** [subodhk01/a2oj#8]
I tested with handle different handles like tourist and VadVergasov even mine but each one of them shoes invalid codeforces handle.

**Comment by subodhk01** [comment]
Hey @codepiyush, I think currently codeforces' APIs are temporarily down, thats why we are getting this error. You can try your handle manually here: https://codeforces.com/api/user.status?handle=subodhk&from=1&count=10 and thanks for pointing out 😉
<img width="717" alt="Screenshot 2020-10-08 at 11 48 50" src="https://user-images.githubusercontent.com/19875783/95422063-3d004080-095c-11eb-9bd7-89df8ded5494.png">

**Comment by subodhk01** [comment]
Now working ✌🏻
